<?php

declare(strict_types=1);
/** @var ReadeckButtonExtension $this */
$instance_url = FreshRSS_Context::userConf()->attributeString('readeck_instance_url');
$api_token = FreshRSS_Context::userConf()->attributeString('readeck_api_token');
$username = FreshRSS_Context::userConf()->attributeString('readeck_username');
$keyboard_shortcut = FreshRSS_Context::userConf()->attributeString('readeck_shortcut');
$button_location = FreshRSS_Context::userConf()->attributeString('readeck_button_location');
$behavior = FreshRSS_Context::userConf()->attributeString('readeck_behavior');
?>

<form action="<?= _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
  <input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken(); ?>" />
  <div class="form-group">
    <label class="group-name" for="readeck_shortcut"><?= _t('ext.readeckButton.configure.keyboard_shortcut'); ?></label>
    <div class="group-controls">
      <input type="text" name="readeck_shortcut" id="readeck_shortcut" maxlength="1" value="<?= $keyboard_shortcut; ?>">
    </div>

    <label class="group-name" for="readeck_behavior"><?= _t('ext.readeckButton.configure.behavior'); ?></label>
    <div class="group-controls">
      <select name="readeck_behavior" id="readeck_behavior">
        <option value="smart" <?= ($behavior == "smart") ? "selected" : "" ?>><?= _t('ext.readeckButton.configure.behavior_smart'); ?></option>
        <option value="link" <?= ($behavior == "link") ? "selected" : "" ?>><?= _t('ext.readeckButton.configure.behavior_link'); ?></option>
        <option value="content" <?= ($behavior == "content") ? "selected" : "" ?>><?= _t('ext.readeckButton.configure.behavior_content'); ?></option>
      </select>
      <p id="behavior_description"><?= _t('ext.readeckButton.configure.behavior_description'); ?></p>
    </div>

    <label class="group-name" for="readeck_button_location"><?= _t('ext.readeckButton.configure.button_location'); ?></label>
    <div class="group-controls">
      <select name="readeck_button_location" id="readeck_button_location">
        <option value="header_bottom" <?= ($button_location == "header_bottom") ? "selected" : "" ?>><?= _t('ext.readeckButton.configure.button_location_header_bottom'); ?></option>
        <option value="header" <?= ($button_location == "header") ? "selected" : "" ?>><?= _t('ext.readeckButton.configure.button_location_header'); ?></option>
        <option value="bottom" <?= ($button_location == "bottom") ? "selected" : "" ?>><?= _t('ext.readeckButton.configure.button_location_bottom'); ?></option>
        <option value="hidden" <?= ($button_location == "hidden") ? "selected" : "" ?>><?= _t('ext.readeckButton.configure.button_location_hidden'); ?></option>
      </select>
    </div>
  </div>

  <div class="form-group form-actions">
    <div class="group-controls">
      <button type="submit" class="btn btn-important"><?= _t('ext.readeckButton.configure.save_changes'); ?></button>
    </div>
  </div>
</form>

<?php if ($this->isEnabled() && (empty($username) || empty($api_token) || empty($instance_url))) : ?>
  <form action="<?= _url('readeckButton', 'requestAccess'); ?>" method="post">
    <input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken(); ?>" />
    <div class="form-group">
      <label class="group-name" for="readeck_instance_url"><?= _t('ext.readeckButton.configure.instance_url'); ?></label>
      <div class="group-controls">
        <input type="url" name="readeck_instance_url" id="readeck_instance_url" title="Please enter a valid URL starting with http:// or https://" value="<?= $instance_url; ?>" required>
      </div>
      <label class="group-name" for="readeck_api_token"><?= _t('ext.readeckButton.configure.api_token'); ?></label>
      <div class="group-controls">
        <input type="password" name="readeck_api_token" id="readeck_api_token" value="<?= $api_token; ?>" required>
      </div>
    </div>

    <div class="alert alert-warn">
      <?= _t('ext.readeckButton.configure.api_token_description'); ?>
    </div>

    <div class="form-group form-actions">
      <div class="group-controls">
        <button type="submit" class="btn btn-important"><?= _t('ext.readeckButton.configure.connect_to_readeck'); ?></button>
      </div>
    </div>
  </form>
<?php elseif (!$this->isEnabled()) : ?>
  <p class="alert alert-error">
    <?= _t('ext.readeckButton.configure.extension_disabled'); ?>
  </p>
<?php endif ?>

<?php if (!empty($username) && !empty($api_token) && !empty($instance_url)) : ?>
  <p class="alert alert-success">
    <?= _t('ext.readeckButton.configure.connected_to_readeck', $username, $instance_url); ?>
  </p>
  <form action="<?= _url('readeckButton', 'revokeAccess'); ?>" method="post">
    <input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken(); ?>" />
    <div class="form-group form-actions">
      <div class="group-controls">
        <button type="submit" class="btn btn-important"><?= _t('ext.readeckButton.configure.revoke_access'); ?></button>
      </div>
    </div>
  </form>
<?php endif ?>