services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    volumes:
      - ./fresh_rss_data:/var/www/FreshRSS/data
      - ./:/var/www/FreshRSS/extensions/freshrss-readeck-button:ro
    ports:
      - 8080:80
